# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_recognizer_api_pb2 as face__recognizer__api__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FaceRecognizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeFace = channel.unary_unary(
                '/FaceRecognizer/RecognizeFace',
                request_serializer=face__recognizer__api__pb2.RecognizeFaceRequest.SerializeToString,
                response_deserializer=face__recognizer__api__pb2.RecognizeFaceResponse.FromString,
                )
        self.Train = channel.unary_unary(
                '/FaceRecognizer/Train',
                request_serializer=face__recognizer__api__pb2.TrainRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class FaceRecognizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFace,
                    request_deserializer=face__recognizer__api__pb2.RecognizeFaceRequest.FromString,
                    response_serializer=face__recognizer__api__pb2.RecognizeFaceResponse.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=face__recognizer__api__pb2.TrainRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FaceRecognizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceRecognizer/RecognizeFace',
            face__recognizer__api__pb2.RecognizeFaceRequest.SerializeToString,
            face__recognizer__api__pb2.RecognizeFaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceRecognizer/Train',
            face__recognizer__api__pb2.TrainRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
