# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_recognizer_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66\x61\x63\x65_recognizer_api.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x14RecognizeFaceRequest\x12\x13\n\x04\x66\x61\x63\x65\x18\x01 \x01(\x0b\x32\x05.Face\"R\n\x15RecognizeFaceResponse\x12\x13\n\x0bperson_name\x18\x01 \x01(\t\x12$\n\rface_location\x18\x02 \x01(\x0b\x32\r.FaceLocation\"8\n\x0cTrainRequest\x12\x13\n\x04\x66\x61\x63\x65\x18\x01 \x01(\x0b\x32\x05.Face\x12\x13\n\x0bperson_name\x18\x02 \x01(\t\"\x14\n\x04\x46\x61\x63\x65\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"H\n\x0c\x46\x61\x63\x65Location\x12\x0c\n\x04left\x18\x01 \x01(\r\x12\x0b\n\x03top\x18\x02 \x01(\r\x12\r\n\x05right\x18\x03 \x01(\r\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\r2\x84\x01\n\x0e\x46\x61\x63\x65Recognizer\x12@\n\rRecognizeFace\x12\x15.RecognizeFaceRequest\x1a\x16.RecognizeFaceResponse\"\x00\x12\x30\n\x05Train\x12\r.TrainRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_recognizer_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOGNIZEFACEREQUEST._serialized_start=58
  _RECOGNIZEFACEREQUEST._serialized_end=101
  _RECOGNIZEFACERESPONSE._serialized_start=103
  _RECOGNIZEFACERESPONSE._serialized_end=185
  _TRAINREQUEST._serialized_start=187
  _TRAINREQUEST._serialized_end=243
  _FACE._serialized_start=245
  _FACE._serialized_end=265
  _FACELOCATION._serialized_start=267
  _FACELOCATION._serialized_end=339
  _FACERECOGNIZER._serialized_start=342
  _FACERECOGNIZER._serialized_end=474
# @@protoc_insertion_point(module_scope)
